site_name: Мой сайт-портфолио
theme:
  name: material
  language: ru   # язык интерфейса сайта
  palette:
      primary: indigo   # основной цвет сайта
      accent: teal   # дополнительный цвет (кнопки, ссылки)

  features:
    - navigation.tabs   # делает меню сверху в виде вкладок
    - navigation.top    # кнопка "вверх страницы"

nav:
  - Home: index.md
  - About: about.md
  - Labs:
      - lab. 1: labs/lab1.md
      - lab. 2: labs/lab2.md
      - lab. 3: labs/lab3.md
      - lab. 4: labs/lab4.md
      - lab. 5: labs/lab5.md