stages:
  - build

build_mkdocs:
  stage: build
  image: python:3.11-slim
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - mkdocs build --strict
  artifacts:
    paths:
      - site/
    expire_in: 30 days